apiVersion: v1
kind: Pod
metadata:
  name: guaranteed
  namespace: default
spec:
  containers:
  - name: qos-demo-guaranteed
    image: ghcr.io/stefanprodan/podinfo:5.1.4
    resources:
      limits:
        memory: "200Mi"
        cpu: "100m"
      requests:
        memory: "200Mi"
        cpu: "100m"